// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Contact() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-2xl mx-auto py-12 px-4\"><h1 class=\"text-3xl font-bold text-slate-800 dark:text-slate-100 mb-2\">Contact</h1><p class=\"text-slate-600 dark:text-slate-300 mb-8\">Get in touch with Keith Thomson for collaboration, project work, and startup enablement.</p><div class=\"space-y-4 text-slate-700 dark:text-slate-200\"><p><span class=\"font-bold\">Name:</span> Keith Thomson</p><p><span class=\"font-bold\">Email:</span> <a class=\"text-neon-pink hover:underline\" href=\"mailto:thomsonk930@gmail.com\">thomsonk930@gmail.com</a></p><p><span class=\"font-bold\">GitHub:</span> <a class=\"text-neon-pink hover:underline\" href=\"https://github.com/whalelogic\" target=\"_blank\" rel=\"noopener noreferrer\">whalelogic</a></p></div><h2 class=\"text-2xl font-bold text-slate-800 dark:text-slate-100 mt-6 mb-2\">Credentials</h2><p class=\"text-slate-600 dark:text-slate-300 mb-8\">A.S., B.S. Computer Science, Google Professional Developer, Security+, AWS Cloud Practitioner, C++ Developer, Python and Go enthusiast.</p><h2 class=\"text-2xl font-bold text-slate-800 dark:text-slate-100 mb-2\">Experience</h2><p class=\"text-slate-600 dark:text-slate-300\">Specialized in startup enablement: helping new companies ship MVPs through software development, cloud engineering, and high-performance backend development in Go and Rust.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Contact").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
