// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Notebook() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<aside class=\"rounded-2xl bg-[#FFFDF5] dark:bg-[#181C14] border border-slate-200 dark:border-neon-amber/30 shadow-sm p-4 h-[600px] flex flex-col relative overflow-hidden\"><div class=\"absolute left-6 top-0 bottom-0 w-px bg-red-300/50 dark:bg-red-500/20\"></div><h2 class=\"font-hand text-2xl text-slate-700 dark:text-neon-amber mb-3 pl-4\">📓 My Trip Notes</h2><div id=\"notebook-entries\" class=\"flex-1 overflow-y-auto pl-4 space-y-3 font-hand text-lg leading-tight text-slate-700 dark:text-slate-200\" style=\"background-image: repeating-linear-gradient(transparent, transparent 31px, rgba(100,100,100,0.15) 32px); background-attachment: local;\"><p class=\"italic text-slate-400 dark:text-slate-500 text-base\">Pin spots from the chat and they'll show up here 📌</p></div><canvas id=\"doodle-canvas\" class=\"mt-3 w-full h-32 rounded-lg bg-white/60 dark:bg-black/20 border border-dashed border-slate-300 dark:border-slate-600 cursor-crosshair\"></canvas><div class=\"flex justify-between items-center mt-1\"><span class=\"text-xs text-slate-400 dark:text-slate-500\">✏️ doodle your route</span> <button id=\"clear-doodle\" class=\"text-xs text-neon-pink hover:underline cursor-pointer\">clear</button></div></aside>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
